/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Gradle plugin project to get you started.
 * For more details on writing Custom Plugins, please refer to https://docs.gradle.org/8.14.2/userguide/custom_plugins.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the Java Gradle plugin development plugin to add support for developing Gradle plugins
    `java-gradle-plugin`
    `maven-publish`

    // Apply the Kotlin JVM plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)
    id("com.gradle.plugin-publish") version "1.3.0"
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

kotlin {
    jvmToolchain(21)
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use Kotlin Test test framework
            useKotlinTest("2.1.20")
        }

        // Create a new test suite
        val functionalTest by registering(JvmTestSuite::class) {
            // Use Kotlin Test test framework
            useKotlinTest("2.1.20")

            dependencies {
                // functionalTest test suite depends on the production code in tests
                implementation(project())
            }

            targets {
                all {
                    // This test suite should run after the built-in test suite has run its tests
                    testTask.configure { shouldRunAfter(test) } 
                }
            }
        }
    }
}

group = "io.composedflavors"
version = "0.0.1-alpha"

gradlePlugin {
    website = "https://github.com/composedflavors/library-consumer-migrator"
    vcsUrl = "https://github.com/composedflavors/library-consumer-migrator.git"

    plugins {
        create("libraryConsumerMigrator") {
            id = "io.composedflavors.library-consumer-migrator"
            implementationClass = "io.composedflavors.libraryconsumermigrator.LibraryConsumerMigratorPlugin"
            displayName = "Library Consumer Migrator"
            description = "Gradle plugin that automates migration of consumer applications as Git submodules into library projects for streamlined testing and development in unified workspace"

            tags = listOf(
                "submodule",
                "git",
                "library",
                "testing",
                "kmp",
                "kotlin-multiplatform",
                "development-tools"
            )
        }
    }
}

gradlePlugin.testSourceSets.add(sourceSets["functionalTest"])

tasks.named<Task>("check") {
    // Include functionalTest as part of the check lifecycle
    dependsOn(testing.suites.named("functionalTest"))
}

publishing {
    publications {
        create<MavenPublication>("pluginMaven") {
            groupId = "io.composedflavors"
            artifactId = "library-consumer-migrator"
            version = "0.0.1-alpha"
        }
    }
    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/composedflavors/library-consumer-migrator")
            credentials {
                username = System.getenv("GITHUB_FLAVOURS_ACTOR")
                password = System.getenv("GITHUB_FLAVOURS_TOKEN")
            }
        }
    }
}