/*
 * This source file was generated by the Gradle 'init' task
 */
package io.composedflavors.libraryconsumermigrator

import io.composedflavors.libraryconsumermigrator.task.MigrateConsumerAppTask
import org.gradle.api.Plugin
import org.gradle.api.Project

/**
 * Gradle plugin for migrating consumer applications into library project as submodules.
 *
 * This plugin helps developers integrate example/consumer applications into their library
 * projects for easier testing and debugging in a unified environment.
 */
class LibraryConsumerMigratorPlugin : Plugin<Project> {

    override fun apply(project: Project) {
        val extension = project.extensions.create(
            EXTENSION_NAME,
            LibraryConsumerMigratorExtension::class.java
        )

        extension.submodulePath.convention(
            project.providers.gradleProperty(PROPERTY_SUBMODULE_PATH)
        )

        extension.submoduleName.convention(
            project.providers.gradleProperty(PROPERTY_SUBMODULE_NAME)
        )

        extension.branch.convention(
            project.providers.gradleProperty(PROPERTY_BRANCH)
        )

        project.tasks.register(TASK_NAME, MigrateConsumerAppTask::class.java) { task ->
            task.group = TASK_GROUP
            task.description = TASK_DESCRIPTION

            task.inputs.property("submodulePath", extension.submodulePath)
            task.inputs.property("submoduleName", extension.submoduleName)
            task.inputs.property("branch", extension.branch).optional(true)
        }
    }

    companion object {
        private const val EXTENSION_NAME = "libraryConsumerMigrator"
        private const val TASK_NAME = "migrateConsumerApp"
        private const val TASK_GROUP = "setup"
        private const val TASK_DESCRIPTION = "Import example application project as a submodule for testing with library modules"

        private const val PROPERTY_SUBMODULE_PATH = "submodulePath"
        private const val PROPERTY_SUBMODULE_NAME = "submoduleName"
        private const val PROPERTY_BRANCH = "branch"
    }
}